# API server listen address
# Defauls to: ":8080" which will listen on all avalable interfaces.
# Overwrite with environment variable: DEVICEAUTH_LISTEN

# listen: :8080

# HTTP Server middleware environment
# Available values:
#   dev - development environment
#   prod - production environment
# Defaults to: prod
# Overwrite with environment variable: DEVICEAUTH_MIDDLEWARE

# middleware: dev

# Mongodb connection string
# Defaults to: mongo-device-auth
# Overwrite with environment variable: DEVICEAUTH_MONGO

# mongo: mongo-device-auth

# Enable SSL for mongo connections
# Defaults to: false
# Overwrite with environment variable: DEVICEAUTH_MONGO_SSL

# mongo_ssl: false

# SkipVerify controls whether a mongo client verifies the
# server's certificate chain and host name.
# If InsecureSkipVerify is true, accepts any certificate
# presented by the server and any host name in that certificate.
# Defaults to: false
# Overwrite with environment variable: DEVICEAUTH_MONGO_SSL_SKIPVERIFY

# mongo_ssl_skipverify: false

# Mongodb username
# Overwrites username set in connection string.
# Defaults to: none
# Overwrite with environment variable: DEVICEAUTH_MONGO_USERNAME

# mongo_username: user

# Mongodb password
# Overwrites password set in connection string.
# Defaults to: none
# Overwrite with environment variable: DEVICEAUTH_MONGO_PASSWORD

# mongo_password: secret

# Workflows service address
# Defaults to: http://mender-workflows-server:8080
# Overwrite with environment variable: DEVICEAUTH_ORCHESTRATOR_ADDR

# orchestrator_addr:  http://mender-workflows-server:8080

# Tenant administration service address (optional)
# Defaults to: none
# Overwrite with environment variable: DEVICEAUTH_TENANTADM_ADDR

# tenantadm_addr:  http://tenantadm

# Default tenant token, for devices that don't supply one (optional)
# Defaults to: none
# Overwrite with environment variable: DEVICEAUTH_DEFAULT_TENANT_TOKEN

# default_tenant_token:  <VALID_TENANT_TOKEN>

# Private key path - used for JWT signing
# Defaults to: /etc/deviceauth/rsa/private.pem
# Overwrite with environment variable: DEVICEAUTH_SERVER_PRIV_KEY_PATH

# server_priv_key_path: /etc/deviceauth/rsa/private.pem

# Fallback private key path - used for JWT verification
# Defaults to: none
# Overwrite with environment variable: DEVICEAUTH_SERVER_FALLBACK_PRIV_KEY_PATH

# server_fallback_priv_key_path: /etc/deviceauth/rsa/private-fallback.pem

# JWT issuer ('iss' claim)
# Defaults to: Mender

# jwt_issuer: Mender

# JWT expiration in seconds ('exp' claim)
# Defaults to: "604800" (one week)

# jwt_exp_timeout: 604800


# Redis address
# Defaults to: "", which disables the Redis cache
# Overwrite with environment variable: DEVICEAUTH_REDIS_ADDR

# redis_addr: ""

# Redis username
# Defaults to: "", which disables the Redis authentication
# Overwrite with environment variable: DEVICEAUTH_REDIS_USERNAME

# redis_username: ""

# Redis password
# Defaults to: "", which disables the Redis authentication
# Overwrite with environment variable: DEVICEAUTH_REDIS_PASSWORD

# redis_password: ""

# Redis DB
# Defaults to: 0
# Overwrite with environment variable: DEVICEAUTH_REDIS_DB

# redis_db: "0"

# Redis client timeout (sec)
# Defaults to: 1
# Overwrite with environment variable: DEVICEAUTH_REDIS_TIMEOUT_SEC

# redis_timeout_sec: "5"

# Redis tenant/device limits expiration(sec)
# Defaults to: 1800 (30mins)
# Overwrite with environment variable: DEVICEAUTH_REDIS_LIMITS_EXPIRE_SEC

# redis_limits_expire_sec: "1800"


#    Enable addon feature restrictions.
#    Defaults to: false
#    Overwrite with environment variable: DEVICEAUTH_HAVE_ADDONS
# have_addons: false
